# Generated by Django 4.2.5 on 2023-10-07 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Имя')),
                ('age', models.IntegerField(verbose_name='Адрес')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
                ('work', models.CharField(max_length=100, verbose_name='Работа')),
            ],
        ),
    ]
